config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "my_events", to: "pages#my_events"
  get "profile", to: "pages#profile"
  get "search_events", to: "pages#search_events"
  get '/events/genre/:genre', to: 'events#index', as: 'events_by_genre'
  get "videocall", to: 'pages#videocall'
  get '/friends/:id', to: 'friendship#show', as: 'friend'

  resources :events, only: [:index, :show, :create, :destroy] do
    resources :user_events, only: :create
    resources :chatrooms, only: :show do
      resources :messages, only: :create
    end
  end
  resources :user_events, only: :destroy
  resources :friendships, only: [:create, :destroy]
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  has_one_attached :photo
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_one :chatroom, dependent: :destroy
  has_many :users, through: :user_events
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user, class_name: "User"
  belongs_to :friend, class_name: "User"

  def other_user(user)
    if self.user == user
      friend
    else
      self.user
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
  def sender?(a_user)
    user.id == a_user.id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :chatrooms
  has_many :events, through: :user_events
  has_many :messages, dependent: :destroy
  has_many :friendships

  has_one_attached :photo

  def is_a_friend?(user)
    Friendship.where(user: self, friend: user).or(Friendship.where(user: user, friend: self)).any?
  end
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :event, uniqueness: { scope: :user_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @event = Event.find(params[:event_id])
    @message = Message.new
    @all_the_people = Message.where(chatroom: @chatroom).map { |record| record.user }.uniq
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: %i[show edit update destroy]

    # @events = Event.all
    # @events = Event.where(venue: "%london%")
  def index
    @events = Event.all
    @events = @events.where("address ILIKE ?", "%#{params[:city]}%") if params[:city].present?
    @events = @events.where(date: params[:date]) if params[:date].present?
    @events = @events.where(genre: params[:genre]) if params[:genre].present?
  end

  def show
    @event = Event.find(params[:id])
    @user_event = UserEvent.find_by(event: @event, user: current_user)

    @markers = [{
        lat: @event.latitude,
        lng: @event.longitude
      }]
  end

  def new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @event.update(params[event_params])
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to event_path, status: :see_other
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :address, :date, :artist, :photo_url)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friendships = current_user.friendships
  end

  def create
    @friendship = Friendship.new(friendship_params)
    @friendship.user = current_user

    if @friendship.save!
      flash[:notice] = "Friend request sent."
      redirect_to profile_path
    else
      flash[:alert] = "Error sending friend request."
      render 'chatroom/show'
    end
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Friendship removed."
    redirect_to profile_path
  end

  def show
    @friend = User.find(params[:id])
  end


  private

  def friendship_params
    params.require(:friendship).permit(:friend_id)
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        message: render_to_string(partial: "message", locals: { message: @message }),
        sender_id: @message.user.id
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def my_events
  end

  def profile
    @user_events = UserEvent.where(user: current_user)
    @friendships = Friendship.where(user: current_user).or(Friendship.where(friend: current_user))
  end

  def videocall
    @chatroom = Chatroom.where(params[:chatroom_id])
  end
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  def create
    @my_event = UserEvent.new
    @event = Event.find(params[:event_id])
    @my_event.event = @event
    @my_event.user = current_user
    @my_event.save!

    redirect_to profile_path
  end

  def destroy
    @user_event = UserEvent.find(params[:id])
    @event = @user_event.event
    @user_event.destroy!
    redirect_to @event
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_events = UserEvent.where(user: @user)
    @friendships = Friendship.where(user: @user).or(Friendship.where(friend: @user))

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/chatrooms/show.html.erb
<% content_for :meta_title, "#{@event.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_image, cl_image_path(@event.photo.key) if @event.photo.attached? %>

<div class="chatroom-banner">
  <%= link_to event_path(@event.id), class: "no-decoration text-white" do %>
    <i class="fa-solid fa-angle-left no-decoration fa-xl people"></i>
  <% end %>
  <p class="chatroom-title"><strong><%= @chatroom.name %> </strong> - Chat</p>

  <%= link_to  videocall_path do %>
    <i class="fa-solid fa-video"></i>
  <% end %>

  <!-- Button trigger modal -->
  <i class="fa-solid fa-people-group fa-xl" data-bs-toggle="modal" data-bs-target="#exampleModal"></i>
</div>

<div class="container chatroom" data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
  data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" style="color: white;" id="exampleModalLabel">Chat Contributers</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <ul class ="contributer-box">
            <% @all_the_people.each do |person| %>
              <li class="person-contributer-box">
                <%= cl_image_tag person.photo.key, height: 40, width: 40, crop: :fill %>
                <%= person.name %>
                <% if person.is_a_friend?(current_user) %>
                  <p><%= person.name %> is already a friend</p>
                <% else %>
                  <%= simple_form_for Friendship.new do |f| %>
                    <%= f.input :friend_id, as: :hidden, input_html: { value: person.id } %>
                    <button type="submit" class="btn" style="color: white">
                      <i class="fa-solid fa-user-plus fa-xl"></i>
                    </button>
                  <% end %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
        <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
          <%= render "messages/message", message: message %>
        </div>
      </div>
    <% end %>
  </div>




 <div class="card-message">
  <%= simple_form_for [@event, @chatroom, @message], html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "chatroom-input-message d-flex" } do |f|%>
      <%= f.input :content,
        label: false,
        placeholder: "Write a message...",
        wrapper_html: {class: "flex-grow-1"}
      %>

      <%= f.submit ">", class: "submit-new-message-buttom" %>

  <% end %>
 </div>
</div>

app/views/events/index.html.erb
<div class="container-swipping">
  <h1 class="title-events">COMING UP</h1>

  <!-- Slider main container -->
  <div data-controller="swiper" class="swiper">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
      <!-- Slides -->
      <%@events.each do |event|%>
      <div class="swiper-slide"><%= link_to event_path(event) do%>
        <img src="<%= event.photo_url%>" alt="">
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>


<div class="container-genre">
  <div class="card-genre">
    <h1 class="title-genre">GENRE</h1>
      <div class= "avatar-index-first-row" >
        <%= link_to events_by_genre_path('Rock'), class: params[:genre] == "Rock" ? "icon-border border-active" : "icon-border" do %>
          <%= image_tag('rock copie.jpg', class: 'avatar') %>
        <% end %>

        <%= link_to events_by_genre_path('Jazz'), class: params[:genre] == "Jazz" ? "icon-border border-active" : "icon-border" do %>
          <%= image_tag('jazz copie.jpg', class: 'avatar') %>
        <% end %>

        <%= link_to events_by_genre_path('Classic'), class: params[:genre] == "Classic" ? "icon-border border-active" : "icon-border"  do %>
          <%= image_tag('classic.jpg', class: 'avatar') %>
        <% end %>

        <%= link_to events_by_genre_path('Electronic'), class: params[:genre] == "Electronic" ? "icon-border border-active" : "icon-border"  do %>
          <%= image_tag('electro.jpg', class: 'avatar') %>
        <% end %>
      </div>
      <div class="avatar-index-second-row">

        <%= link_to events_by_genre_path('Blues'), class: params[:genre] == "Blues" ? "icon-border border-active" : "icon-border"  do %>
          <%= image_tag('blues copie.jpg', class: 'avatar') %>
        <% end %>

        <%= link_to events_by_genre_path('Pop'), class: params[:genre] == "Pop" ? "icon-border border-active" : "icon-border"  do %>
          <%= image_tag('pop-good.jpg', class: 'avatar') %>
        <% end %>

        <%= link_to events_by_genre_path('R&B'), class: params[:genre] == "R&B" ? "icon-border border-active" : "icon-border"  do %>
          <%= image_tag('r&b.jpg', class: 'avatar') %>
        <% end %>

        <%= link_to events_by_genre_path('Rap'), class: params[:genre] == "Rap" ? "icon-border border-active" : "icon-border" do %>
          <%= image_tag('rap copie.jpg', class: 'avatar') %>
        <% end %>
      </div>
    </div>
  </div>
</div>




<h1 class="title-events-index">EVENTS</h1>


<div class="events-list-index">
  <div class="cards-event">
    <% @events.each do |event| %>
      <div class="card-event-index">
        <%= link_to event_path(event), class: "no-decoration" do %>
          <img src="<%= event.photo_url%>" alt="">
          <div class="card-text-index">
            <div class="text-left">
              <h2 class="card-title-index"><%= event.name.upcase %></h2>
              <h2 class="card-artist-index"><%= content_tag :i, "", class: "fa light fa-location-dot" %> &nbsp; <%= event.address %></h2>
            </div>
            <div class="text-right">
              <p class="card-date-index"><%= event.date.strftime('%d-%m') %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1>Live aid</h1>

app/views/events/show.html.erb
<% content_for :meta_title, "#{@event.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @event.description %>
<% content_for :meta_image, cl_image_path(@event.photo.key) if @event.photo.attached? %>


<div class ="back-to-index d-flex">
<%= link_to events_path , class: "no-decoration text-white pe-2" do %>
  <i class="fa-solid fa-angle-left backtick"></i>
<% end %>
</div>
<div class="event-name"><%= @event.name %></div>

<div class="show-margin">
  <img src=<%= @event.photo_url %> class="show-event-banner">
</div>


<div class="event-card-detail">

  <div class="event-card-detail-name">
    <%= @event.name %>
  </div>


  <div class="event_card_text">
    <%= content_tag :i, "", class: "fa light fa-location-dot" %>  <%= @event.address%>
    <br>
    <br>
    <%= content_tag :i, "", class: "fa light fa-calendar" %>  <%= @event.date.strftime('%d-%m-%Y') %>
    <br>
    <br>
    <%= content_tag :i, "", class: "fa light fa-clock" %>  <%= @event.date.strftime("%I:%m %p") %>
  </div>

  <div class="line-up">
    <p class="d-flex justify-content-center"><strong>Line Up</strong></p>
    <p class="d-flex justify-content-center"><%= @event.artist%><p>
  </div>

  <div class="more-information">
    <p class="d-flex justify-content-center"><u><strong>More Information</strong></u></p>
    <p class="d-flex justify-content-center" style="text-align: justify"><%= @event.description%></p>
  </div>

  <div>
    <div class="find_us_text">
      <p><strong>Interested?</strong></p>
    </div>
    <div class="center-button">
      <div>
        <% if @user_event %>
          <%= link_to "Remove Event", user_event_path(@user_event), data: { turbo_method: :delete }, class:"remove-event-show-event-page" %>
        <% else %>
          <%= form_tag(event_user_events_path(@event), method: :post) do %>
            <%= hidden_field_tag :trigger_method, true %>
            <%= submit_tag 'Add to My Events' , class: "interested_button" %>
          <% end %>
        <% end %>
      <div>
      <div class="top-button-interested">
        <%= link_to event_chatroom_path(@event, @event.chatroom) do %>
          <button class="interested_button">Join Chatroom</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="find_us_text">
  <p><strong>VENUE</strong></p>
</div>

<div class="card-map">
  <div style="width: 80%; height: 300px; border-radius: 20px; border-style: solid; border-color: black; border-style: solid; border-color: white; border-width: 5px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/friendships/index.html.erb
<%= @friendships %>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.name %></strong>
  </small>
  <p><%= message.content%></p>
  <i class="fa-xs d-flex justify-content-end"><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
</div>

app/views/pages/home.html.erb
<div class="home-top-container">
  <div class="card-home-text">
    <h1 class="card-home-text-h1">Chromatic</h1>
    <h2 class="card-home-text-h2">Discover events near you<br>and meet new people<br>along the way</h2>
  </div>
</div>

<div class="lets-go-button">
  <%= link_to "Let's go!", events_path, class:"btn btn-flat d-flex justify-content-center offset-button" %>
</div>

app/views/pages/my_events.html.erb
<h1>hi from my events page</h1>

app/views/pages/profile.html.erb
<div class="profile-page-container">


  <div class ="back-to-index d-flex">
    <%= link_to events_path , class: "no-decoration text-white pe-2" do %>
      <i class="fa-solid fa-angle-left backtick"></i>
    <% end %>
    <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link-logout no-decoration text-white" %>
  </div>


  <div class="profile-hello" >
    <div class="avatar-profile">
    <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, class: 'avatar-header-profile', crop: :fill %>
    <% else %>
      <%= image_tag "user-image.jpg", class: 'avatar-header-profile' %>
    <% end %>
    </div>
    <h1 class="title-profile-name">Hello <%= current_user.name %></h1>
  </div>


  <div class="container-profile-everything">

    <div class="container-swipping">
        <h1 class="title-event">MY EVENTS</h1>
        <% if @user_events.empty? %>
          <p class="no-event"> No events added 😢</p>
        <% else %>
        <!-- Slider main container -->
          <div data-controller="swiper" class="swiper">
          <!-- Additional required wrapper -->
          <div class="swiper-wrapper">
            <!-- Slides -->
            <% @user_events.each do |user_event| %>
              <div class="swiper-slide">
                <%= link_to event_path(user_event.event) do%>
                  <img src="<%= user_event.event.photo_url%>" alt="">
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>




  <div class="container-friend">
  <div class="card-friend">
    <h1 class="title-friend">FRIENDS</h1>
      <% if @friendships.empty? %>
        <p class="no-friend"> No friends added yet 😢</p>
      <% else %>
        <% @friendships.each do |friendship| %>
        <%= link_to user_path(friendship.other_user(current_user)) do %>
          <div class="friendsprofile">
          <%= cl_image_tag friendship.other_user(current_user).photo.key, class: 'avatar-friend-profile', crop: :fill %>
          <p class="friend-name"><%= friendship.other_user(current_user).name %></p>
          <%= link_to friendship_path(friendship), data: { turbo_method: :delete } do %>
            <i class="fa-solid fa-user-minus"></i>
          <% end %>
        <% end %>
        </div>
      <% end %>
        <%# <div class= "avatar-index-first-row">
          <img src="https://ca.slack-edge.com/T02NE0241-U03BXKTHCEM-560844b1dce0-512" class="card-pop avatar" />
          <img src="https://ca.slack-edge.com/T02NE0241-U02KV2K84JJ-268a6271db86-512" class="card-pop avatar" />
          <img src="https://ca.slack-edge.com/T02NE0241-U03BLPQSHA6-f3eb46882dab-512" class="card-pop avatar" />
          <img src="https://ca.slack-edge.com/T02NE0241-U03BKK2DNLB-843021afbdb3-512" class="card-pop avatar" />
        </div>
        <div class="avatar-index-second-row">
          <img src="https://ca.slack-edge.com/T02NE0241-U03BCJ6HNP8-374030a92114-512" class="card-pop avatar" />
          <img src="https://ca.slack-edge.com/T02NE0241-U03Q1L5102V-8f5bffc920e3-512" class="card-pop avatar" />
          <img src="https://ca.slack-edge.com/T02NE0241-U045Q0RPL0K-111a908ca1f8-512" class="card-pop avatar" />
          <img src="https://ca.slack-edge.com/T02NE0241-U03PRDJEMNG-c649a4eb21a3-512" class="card-pop avatar" />
        </div> %>
        <% end %>
      </div>
    </div>
  </div>
</div>
 </div>

app/views/pages/search_events.html.erb
<div class="home-top-container">
  <h1 class="card-home-text-h1">Chromatic</h1>
  <h2 class="card-home-text-h2">Discover events near you<br>and meet new people<br>along the way</h2>
</div>

<div class="container findevent"form id="findeventForm" action="">
    <h2 class="findeventtitle">Find Event</h2>
    <div class="content-container">
        <%= form_with url: events_path, method: :get, class: 'date' do %>
          <%= text_field_tag :city,
          params[:city],
          class: "form-control",
          placeholder: "Location"
          %>
          <%= date_field_tag :date%>
          <%= submit_tag "Start", class: "btn btn-flat btn-centre" %>
        <% end %>
    </div>
  </div>
    <br>
    <br>

app/views/pages/videocall.html.erb
  <!--  CHATROOM-->
  <div class="chatroom-container">
  <div id="video-button-back">
    <%= link_to events_path do %>
      <i class="fa-solid fa-chevron-left"></i>
    <% end %>
  </div>
    <button class="stream-button" id="join-btn">Join Stream</button>

    <div class="chatroom-card">


      <div id="stream-wrapper">

        <div id="video-streams"></div>

        <div class="card-controlers">

           <div id="stream-controls">
              <button class="stream-controller-button" id="leave-btn">Leave Stream</button>
              <button  class="stream-controller-button" id="mic-btn">Mic On</button>
              <button  class="stream-controller-button" id="camera-btn">Camera on</button>
          </div>

      </div>

    </div>

  </div>
  <!-- CHATROOM -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">

  <%= link_to search_events_path, class: 'nav-event d-flex justify-content-center flex-column text-decoration-none text-white' do %>
    <button class="button-search"type="button"><i class="fa-solid fa-magnifying-glass"></i></button>
    <p class="navbar-p"></p>
  <% end %>

  <%= link_to profile_path, class: 'nav-profile d-flex justify-content-center flex-column text-decoration-none text-white' do %>
    <% if current_user.photo.attached? %>
     <%= cl_image_tag current_user.photo.key, class: "avatar-navbar", alt: 'avatar' %>
    <% else %>
      <%= image_tag "user-image.jpg", class: "avatar-navbar"%>
    <% end %>
    <button class="button-profile"type="button"></button>
    <p class="navbar-p"></p>
  <% end %>
</div>

app/views/users/show.html.erb
<% content_for :meta_title, "#{@user.name } is on #{DEFAULT_META["meta_product_name"]}" %>


<div class="profile-page-container">

  <div class ="back-to-index d-flex">
    <%= link_to events_path , class: "no-decoration text-white pe-2" do %>
      <i class="fa-solid fa-angle-left backtick"></i>
    <% end %>
    <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link-logout no-decoration text-white" %>
  </div>


  <div class="profile-hello" >
    <div class="avatar-profile">
    <% if @user.photo.attached? %>
      <%= cl_image_tag @user.photo.key, class: 'avatar-header-profile', crop: :fill %>
    <% else %>
      <%= image_tag "classic.jpg" %>
    <% end %>
    </div>
    <h1 class="title-profile-name">Hello <%= @user.name %></h1>
  </div>


  <div class="container-profile-everything">

    <div class="container-swipping">
      <h1 class="title-events">MY EVENTS</h1>

      <!-- Slider main container -->
      <div data-controller="swiper" class="swiper">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
          <!-- Slides -->
          <% @user_events.each do |user_event| %>
            <div class="swiper-slide">
              <%= link_to event_path(user_event.event) do%>
                <img src="<%= user_event.event.photo_url%>" alt="">
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>



  <div class="container-genre">
  <div class="card-genre">
    <h1 class="title-friend">FRIENDS</h1>
      <% if @friendships.empty? %>
        <p class="friend-name">no friend added</p>
      <% else %>
        <% @friendships.each do |friendship| %>
        <%= link_to user_path(friendship.user) do %>
          <div class="friendsprofile">
          <%= cl_image_tag friendship.other_user(@user).photo.key, class: 'avatar-friend-profile', crop: :fill %>
          <p class="friend-name"><%= friendship.other_user(@user).name %></p>
          <%= link_to friendship_path(friendship), data: { turbo_method: :delete } do %>
          <i class="fa-solid fa-user-minus"></i>
          <% end %>
        <% end %>
        </div>
      <% end %>
        <%# <div class= "avatar-index-first-row">
          <img src="https://ca.slack-edge.com/T02NE0241-U03BXKTHCEM-560844b1dce0-512" class="card-pop avatar" />
          <img src="https://ca.slack-edge.com/T02NE0241-U02KV2K84JJ-268a6271db86-512" class="card-pop avatar" />
          <img src="https://ca.slack-edge.com/T02NE0241-U03BLPQSHA6-f3eb46882dab-512" class="card-pop avatar" />
          <img src="https://ca.slack-edge.com/T02NE0241-U03BKK2DNLB-843021afbdb3-512" class="card-pop avatar" />
        </div>
        <div class="avatar-index-second-row">
          <img src="https://ca.slack-edge.com/T02NE0241-U03BCJ6HNP8-374030a92114-512" class="card-pop avatar" />
          <img src="https://ca.slack-edge.com/T02NE0241-U03Q1L5102V-8f5bffc920e3-512" class="card-pop avatar" />
          <img src="https://ca.slack-edge.com/T02NE0241-U045Q0RPL0K-111a908ca1f8-512" class="card-pop avatar" />
          <img src="https://ca.slack-edge.com/T02NE0241-U03PRDJEMNG-c649a4eb21a3-512" class="card-pop avatar" />
        </div> %>
        <% end %>
      </div>
    </div>
  </div>
</div>